### ISSUE TITLE
TeamCity module not working on the first run

### ISSUE THREAD

**Issue by madben2000** [cake-contrib/Cake.BuildSystems.Module#20] opened 2018-09-25 13:43 UTC
Hey,

I added Cake.BuildSystems.Module to tools/Modules/packages.config as described.
The first run on TeamCity the module is not working. If I run it the second time it is.
So whenever a new Branch "runs" on the TeamCity server the module is not working since you "run" the branch a second time. The Cake.BuildSystems.Module folder and its content itself I did not check into source control. What am I doing wrong?

**Comment by agc93** [comment] 2018-09-29 11:36
That's a bit odd, and I haven't seen that before 😐 

Can you get a run with Diagnostic Verbosity and upload the log to Gist/pastebin/etc (make sure to obfuscate any sensitive info)? That might give some hints...

**Comment by madben2000** [comment] 2018-10-02 12:14
Latest versions. Cake 0.30.0, BuildSystems.Module 0.3.1
When I inspect the logs on the first run there is:
[13:38:02] :	 [Step 2/2] Preparing to run build script...
[13:38:04] :	 [Step 2/2] Running build script...
[13:38:04] :	 [Step 2/2] Module directory does not exist.
[13:38:04] :	 [Step 2/2] NuGet.config not found.
[13:38:04] :	 [Step 2/2] Analyzing build script...
[13:38:04] :	 [Step 2/2] Analyzing C:/TeamCity/buildAgent3/work/80c1d37f1bf12ba5/PSS/App/build.cake...
[13:38:04] :	 [Step 2/2] Processing build script...
[13:38:04] :	 [Step 2/2] Installing tools...
.....
[13:38:05] :	 [Step 2/2] Installing addins...
so it is only installing Tools and Addins


When the script is build a second time, the log looks like:
[13:39:56]
[Step 2/2] Preparing to run build script...
[13:39:59]
[Step 2/2] Running build script...
[13:39:59]
[Step 2/2] Verifying assembly 'Cake.MyGet.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
[13:39:59]
[Step 2/2] Verifying assembly 'Cake.TeamCity.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
[13:39:59]
[Step 2/2] Verifying assembly 'Cake.TFBuild.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
[13:39:59]
[Step 2/2] Verifying assembly 'Cake.TravisCI.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
[13:39:59]
[Step 2/2] Registering module Cake.MyGet.Module.MyGetModule...
[13:39:59]
[Step 2/2] Registering module Cake.TeamCity.Module.TeamCityModule...
[13:39:59]
[Step 2/2] Registering module Cake.TFBuild.Module.TFBuildModule...
[13:39:59]
[Step 2/2] Registering module Cake.TravisCI.Module.TravisCIModule...
[13:40:00]
[Step 2/2] Verifying assembly 'Cake.Git, Version=0.19.0.0, Culture=neutral, PublicKeyToken=null'.
[13:40:00]
[Step 2/2] Verifying assembly 'LibGit2Sharp, Version=0.25.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333'.
[13:40:00]
[Step 2/2] Verifying assembly 'ICSharpCode.SharpZipLib, Version=1.0.0.999, Culture=neutral, PublicKeyToken=1b03e6acf1164f73'.
[13:40:00]
[Step 2/2] Verifying assembly 'Cake.Compression, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null'.

And everything works like expected.

**Comment by nils-a** [comment] 2021-01-25 22:59
Sorry, really late reply here.
> [13:38:04] : [Step 2/2] Module directory does not exist.

I only get this output line, when I forget to bootstrap the module.
i.e. If you're normally running `.\build.ps1 cake.build --targe=Default`, be sure to also run `.\build.ps1 cake.build --bootstrap` first.

**Comment by nils-a** [comment] 2021-02-02 19:52
Since this is an older issue and I am currently unable to reproduce the problem, I'll go ahead and close this issue.
If the problem persists, feel free to open a new issue.

**Closed by nils-a** 2021-02-02 19:52 UTC
